services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      redis-net:
        ipv4_address: 172.25.0.10

  redis-replica1:
    image: redis:latest
    hostname: redis-replica1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-replica.conf:/usr/local/etc/redis/redis.conf  
    ports:
      - "6380:6379"
    networks:
      redis-net:
        ipv4_address: 172.25.0.11

  redis-replica2:
    image: redis:latest
    hostname: redis-replica2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-replica.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6381:6379"
    networks:
      redis-net:
        ipv4_address: 172.25.0.12

  redis-replica3:
    image: redis:latest
    hostname: redis-replica3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-replica.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6382:6379"
    networks:
      redis-net:
        ipv4_address: 172.25.0.13

  sentinel1:
    image: redis:latest
    hostname: sentinel1
    command: sh -c "sleep 5 && redis-sentinel /usr/local/etc/redis/sentinel.conf"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    depends_on:
      redis-master:
        condition: service_healthy
    restart: on-failure
    networks:
      - redis-net

  sentinel2:
    image: redis:latest
    hostname: sentinel2
    command: sh -c "sleep 5 && redis-sentinel /usr/local/etc/redis/sentinel.conf"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    depends_on:
      redis-master:
        condition: service_healthy
    restart: on-failure
    networks:
      - redis-net

  sentinel3:
    image: redis:latest
    hostname: sentinel3
    command: sh -c "sleep 5 && redis-sentinel /usr/local/etc/redis/sentinel.conf"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    depends_on:
      redis-master:
        condition: service_healthy
    restart: on-failure
    networks:
      - redis-net

  failover-manager:
      build: 
        context: ./failover
        dockerfile: failover_dockerfile
      command: python /usr/src/app/failover.py
      restart: "no" 
      networks:
        - redis-net
      volumes:
        - ./logs_failover:/usr/src/app/logs
networks:
  redis-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24 # Definir la subred
        gateway: 172.25.0.1 # Definir el gateway 